markdown: kramdown
highlighter: rouge
title: 'Nickolas Burr'
tagline: 'Statically-typed, polyglottal Buffalonian'
description: 'Nickolas Burr is an American software developer from Buffalo, NY, USA.'
location: 'Buffalo, NY, USA'
url: https://blog.nickolasburr.com
author:
  name: 'Nickolas Burr'
  url: https://github.com/nickolasburr
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
version: 3.7.1
sidebar_home_link: true
github:
  profile: https://github.com/nickolasburr
disqus:
  shortname: nickolasburr
google_analytics: 'UA-113897119-3'
