markdown: kramdown
highlighter: rouge
title: "Nickolas Burr"
tagline: "Dynamically-typed, garbage-collected Buffalonian."
description: "My name is Nickolas Burr and I'm a Magento developer from Buffalo, NY. I use this space to discuss everything from software design patterns to personal growth, and a whole lot in between."
location: "Buffalo, NY, USA"
url: https://blog.nickolasburr.com
author:
  name: "Nickolas Burr"
  url: https://github.com/nickolasburr
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
version: 3.7.1
sidebar_home_link: true
github:
  profile: https://github.com/nickolasburr
disqus:
  shortname: nickolasburr
google_analytics: "UA-113897119-3"
